# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_win_inputData.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_win_inputData(object):
    def setupUi(self, win_inputData):
        win_inputData.setObjectName("win_inputData")
        win_inputData.setWindowModality(QtCore.Qt.WindowModal)
        win_inputData.setEnabled(True)
        win_inputData.resize(855, 534)
        self.groupBox = QtWidgets.QGroupBox(win_inputData)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 416, 526))
        self.groupBox.setObjectName("groupBox")
        self.label_rawPic = QtWidgets.QLabel(self.groupBox)
        self.label_rawPic.setGeometry(QtCore.QRect(10, 80, 391, 431))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_rawPic.setFont(font)
        self.label_rawPic.setTextFormat(QtCore.Qt.AutoText)
        self.label_rawPic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rawPic.setObjectName("label_rawPic")
        self.button_choosePic = QtWidgets.QPushButton(self.groupBox)
        self.button_choosePic.setGeometry(QtCore.QRect(5, 30, 86, 32))
        self.button_choosePic.setObjectName("button_choosePic")
        self.edit_picPath = QtWidgets.QTextEdit(self.groupBox)
        self.edit_picPath.setGeometry(QtCore.QRect(90, 30, 316, 31))
        self.edit_picPath.setDocumentTitle("")
        self.edit_picPath.setObjectName("edit_picPath")
        self.groupBox_3 = QtWidgets.QGroupBox(win_inputData)
        self.groupBox_3.setGeometry(QtCore.QRect(425, 5, 421, 296))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_faceImg = QtWidgets.QLabel(self.groupBox_3)
        self.label_faceImg.setGeometry(QtCore.QRect(115, 55, 181, 196))
        self.label_faceImg.setText("")
        self.label_faceImg.setPixmap(QtGui.QPixmap("../../../Pictures/IMG_0198.jpg"))
        self.label_faceImg.setScaledContents(True)
        self.label_faceImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_faceImg.setObjectName("label_faceImg")
        self.comboBox_chooseName = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_chooseName.setGeometry(QtCore.QRect(110, 250, 146, 46))
        self.comboBox_chooseName.setObjectName("comboBox_chooseName")
        self.label_pleaseChooseName = QtWidgets.QLabel(self.groupBox_3)
        self.label_pleaseChooseName.setGeometry(QtCore.QRect(30, 265, 76, 16))
        self.label_pleaseChooseName.setObjectName("label_pleaseChooseName")
        self.button_lastFace = QtWidgets.QPushButton(self.groupBox_3)
        self.button_lastFace.setEnabled(False)
        self.button_lastFace.setGeometry(QtCore.QRect(35, 110, 65, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_lastFace.sizePolicy().hasHeightForWidth())
        self.button_lastFace.setSizePolicy(sizePolicy)
        self.button_lastFace.setCheckable(True)
        self.button_lastFace.setObjectName("button_lastFace")
        self.button_nextFace = QtWidgets.QPushButton(self.groupBox_3)
        self.button_nextFace.setEnabled(False)
        self.button_nextFace.setGeometry(QtCore.QRect(300, 110, 65, 120))
        self.button_nextFace.setObjectName("button_nextFace")
        self.button_nameConfirm = QtWidgets.QPushButton(self.groupBox_3)
        self.button_nameConfirm.setGeometry(QtCore.QRect(255, 255, 114, 32))
        self.button_nameConfirm.setObjectName("button_nameConfirm")
        self.label_recogNote = QtWidgets.QLabel(self.groupBox_3)
        self.label_recogNote.setGeometry(QtCore.QRect(25, 30, 371, 41))
        self.label_recogNote.setObjectName("label_recogNote")
        self.label_faceImg.raise_()
        self.comboBox_chooseName.raise_()
        self.label_pleaseChooseName.raise_()
        self.button_nextFace.raise_()
        self.button_nameConfirm.raise_()
        self.label_recogNote.raise_()
        self.button_lastFace.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(win_inputData)
        self.groupBox_2.setGeometry(QtCore.QRect(425, 295, 421, 236))
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_nameInDB = QtWidgets.QTableView(self.groupBox_2)
        self.table_nameInDB.setGeometry(QtCore.QRect(260, 30, 136, 191))
        self.table_nameInDB.setBaseSize(QtCore.QSize(2, 2))
        self.table_nameInDB.setLineWidth(2)
        self.table_nameInDB.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_nameInDB.setIconSize(QtCore.QSize(2, 2))
        self.table_nameInDB.setObjectName("table_nameInDB")
        self.table_confirmedNames = QtWidgets.QTableView(self.groupBox_2)
        self.table_confirmedNames.setGeometry(QtCore.QRect(15, 30, 146, 181))
        self.table_confirmedNames.setFrameShape(QtWidgets.QFrame.VLine)
        self.table_confirmedNames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_confirmedNames.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_confirmedNames.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_confirmedNames.setObjectName("table_confirmedNames")
        self.button_addData2DB = QtWidgets.QPushButton(self.groupBox_2)
        self.button_addData2DB.setGeometry(QtCore.QRect(165, 50, 91, 41))
        self.button_addData2DB.setObjectName("button_addData2DB")
        self.button_clearCache = QtWidgets.QPushButton(self.groupBox_2)
        self.button_clearCache.setGeometry(QtCore.QRect(165, 100, 91, 41))
        self.button_clearCache.setObjectName("button_clearCache")
        self.button_back2main = QtWidgets.QPushButton(self.groupBox_2)
        self.button_back2main.setGeometry(QtCore.QRect(165, 150, 91, 41))
        self.button_back2main.setObjectName("button_back2main")

        self.retranslateUi(win_inputData)
        QtCore.QMetaObject.connectSlotsByName(win_inputData)

    def retranslateUi(self, win_inputData):
        _translate = QtCore.QCoreApplication.translate
        win_inputData.setWindowTitle(_translate("win_inputData", "录入人脸数据"))
        self.groupBox.setTitle(_translate("win_inputData", "原始图像"))
        self.label_rawPic.setText(_translate("win_inputData", "请选择图片"))
        self.button_choosePic.setText(_translate("win_inputData", "选择图片"))
        self.groupBox_3.setTitle(_translate("win_inputData", "录入人名"))
        self.label_pleaseChooseName.setText(_translate("win_inputData", "请选择人名："))
        self.button_lastFace.setText(_translate("win_inputData", "上一张"))
        self.button_nextFace.setText(_translate("win_inputData", "下一张"))
        self.button_nameConfirm.setText(_translate("win_inputData", "确认"))
        self.label_recogNote.setText(_translate("win_inputData", "<html><head/><body><p>选择照片后将自动识别人脸。</p><p><br/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("win_inputData", "数据库操作"))
        self.button_addData2DB.setText(_translate("win_inputData", "录入数据库"))
        self.button_clearCache.setText(_translate("win_inputData", "清空缓存"))
        self.button_back2main.setText(_translate("win_inputData", "返回主界面"))

